import { useEffect, useState } from 'react';
import Sidebar from '../components/Sidebar';
import { inventoryApi } from '../services/inventoryApi';

export default function InventorySetup() {
  const [categories, setCategories] = useState([]); const [suppliers, setSuppliers] = useState([]); const [categoryName, setCategoryName] = useState(''); const [supplierName, setSupplierName] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); try { const [categoryResult, supplierResult] = await Promise.all([inventoryApi.getCategories(), inventoryApi.getSuppliers()]); setCategories(categoryResult.data.categories || []); setSuppliers(supplierResult.data.suppliers || []); setError(''); } catch (requestError) { setError(requestError.message || 'Inventory setup data could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const createCategory = async (event) => { event.preventDefault(); setSaving(true); try { await inventoryApi.createCategory({ name: categoryName }); setCategoryName(''); setNotice('Category created. Use its ID when adding inventory.'); await load(); } catch (requestError) { setError(requestError.message || 'Unable to create category.'); } finally { setSaving(false); } };
  const createSupplier = async (event) => { event.preventDefault(); setSaving(true); try { await inventoryApi.createSupplier({ name: supplierName }); setSupplierName(''); setNotice('Supplier created. Use its ID when adding inventory.'); await load(); } catch (requestError) { setError(requestError.message || 'Unable to create supplier.'); } finally { setSaving(false); } };
  return <div className="dashboard-shell"><Sidebar /><main className="reports-page"><header className="reports-header"><div><span className="eyebrow">Inventory setup</span><h1>Categories & suppliers</h1><p>Create the master data required before adding inventory.</p></div><button className="secondary-button" type="button" onClick={load}>Refresh</button></header>{error && <div className="form-message form-message--error">{error}<button type="button" onClick={() => setError('')}>×</button></div>}{notice && <div className="form-message form-message--success">{notice}<button type="button" onClick={() => setNotice('')}>×</button></div>}<section className="report-chart-grid"><article><h2>Categories</h2><form className="auth-form" onSubmit={createCategory}><label>Name<input required value={categoryName} onChange={(event) => setCategoryName(event.target.value)} placeholder="Produce" /></label><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Add category'}</button></form><table className="report-table"><thead><tr><th>ID</th><th>Name</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan="3">Loading…</td></tr> : categories.length ? categories.map((category) => <tr key={category.id}><td>{category.id}</td><td>{category.name}</td><td>{category.isActive ? 'Active' : 'Inactive'}</td></tr>) : <tr><td colSpan="3">No categories yet.</td></tr>}</tbody></table></article><article><h2>Suppliers</h2><form className="auth-form" onSubmit={createSupplier}><label>Name<input required value={supplierName} onChange={(event) => setSupplierName(event.target.value)} placeholder="Supplier name" /></label><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Add supplier'}</button></form><table className="report-table"><thead><tr><th>ID</th><th>Name</th><th>Status</th></tr></thead><tbody>{loading ? <tr><td colSpan="3">Loading…</td></tr> : suppliers.length ? suppliers.map((supplier) => <tr key={supplier.id}><td>{supplier.id}</td><td>{supplier.name}</td><td>{supplier.isActive ? 'Active' : 'Inactive'}</td></tr>) : <tr><td colSpan="3">No suppliers yet.</td></tr>}</tbody></table></article></section></main></div>;
}
