import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import Sidebar from '../components/Sidebar';
import { inventoryApi } from '../services/inventoryApi';
import { employeeApi } from '../services/employeeApi';

const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
const number = (value) => Number(value || 0);
const reportOptions = [
  ['inventory', 'Inventory summary', 'Stock value, status, and category allocation.'],
  ['low-stock', 'Low stock report', 'Items requiring replenishment now.'],
  ['movements', 'Stock movements', 'Recorded stock activity and reasons.'],
  ['employees', 'Employee overview', 'Workforce status and department distribution.'],
];
const statusLabel = { IN_STOCK: 'In stock', LOW_STOCK: 'Low stock', OUT_OF_STOCK: 'Out of stock' };

export default function Reports() {
  const [inventory, setInventory] = useState([]), [inventorySummary, setInventorySummary] = useState({}), [lowStock, setLowStock] = useState([]), [movements, setMovements] = useState([]), [employees, setEmployees] = useState([]), [employeeSummary, setEmployeeSummary] = useState({});
  const [active, setActive] = useState('inventory'), [loading, setLoading] = useState(true), [error, setError] = useState(''), [updated, setUpdated] = useState(null), [movementType, setMovementType] = useState('');
  const load = async () => { setLoading(true); try { const [items, summary, low, history, people, peopleSummary] = await Promise.all([inventoryApi.getInventory({ page: 1, limit: 100 }), inventoryApi.getSummary(), inventoryApi.getLowStock(), inventoryApi.getMovements(), employeeApi.getEmployees({ page: 1, limit: 100 }), employeeApi.getSummary()]); setInventory(items.data.items || []); setInventorySummary(summary.data.summary || {}); setLowStock(low.data.items || []); setMovements(history.data.movements || []); setEmployees(people.data.employees || []); setEmployeeSummary(peopleSummary.data.summary || {}); setUpdated(new Date()); setError(''); } catch (requestError) { setError(requestError.message || 'Reports could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const inventoryStatus = useMemo(() => [{ name: 'Healthy', value: number(inventorySummary.healthyStockCount), color: '#397a3f' }, { name: 'Low stock', value: number(inventorySummary.lowStockCount), color: '#dc8a25' }, { name: 'Out of stock', value: number(inventorySummary.outOfStockCount), color: '#d94b42' }], [inventorySummary]);
  const departments = useMemo(() => Object.values(employees.reduce((all, employee) => { const key = employee.department || 'Unassigned'; all[key] = all[key] || { name: key, employees: 0 }; all[key].employees += 1; return all; }, {})), [employees]);
  const filteredMovements = useMemo(() => movements.filter((movement) => !movementType || movement.type === movementType), [movements, movementType]);
  const title = reportOptions.find((item) => item[0] === active) || reportOptions[0];
  const metrics = [['Inventory items', inventorySummary.totalItems || 0, 'Tracked SKUs'], ['Inventory value', money.format(number(inventorySummary.totalInventoryValue)), 'Current stock value'], ['Low stock', inventorySummary.lowStockCount || 0, 'Needs replenishment'], ['Employees', employeeSummary.totalEmployees || 0, String(employeeSummary.activeEmployees || 0) + ' active']];
  return <div className="dashboard-shell"><Sidebar /><motion.main className="reports-page" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}><header className="reports-header"><div><span className="eyebrow">Business intelligence</span><h1>Reports</h1><p>Review business performance and operational data.</p></div><div className="reports-header__actions"><span className="timestamp-pill">Updated {updated ? updated.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}</span><button className="secondary-button" type="button" onClick={load}>Refresh</button></div></header>
    {error && <div className="form-message form-message--error">{error}<button type="button" onClick={() => setError('')}>×</button></div>}
    <section className="reports-metrics">{metrics.map(([label, value, detail], index) => <motion.article key={label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }}><span>{label}</span><strong>{value}</strong><small>{detail}</small></motion.article>)}</section>
    <section className="reports-categories"><div className="report-section-heading"><div><span className="eyebrow">Report library</span><h2>Operational reports</h2></div><span>{reportOptions.length} available reports</span></div><div className="report-card-grid">{reportOptions.map(([key, name, description], index) => <motion.button key={key} type="button" className={'report-card ' + (active === key ? 'report-card--active' : '')} onClick={() => setActive(key)} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }}><i>{index + 1}</i><strong>{name}</strong><span>{description}</span><b>View report →</b></motion.button>)}</div></section>
    <section className="report-workspace"><header><div><span className="eyebrow">Detailed report</span><h2>{title[1]}</h2><p>{title[2]}</p></div>{active === 'movements' && <select value={movementType} onChange={(e) => setMovementType(e.target.value)}><option value="">All movements</option><option value="IN">Stock in</option><option value="OUT">Stock out</option><option value="ADJUSTMENT">Adjustment</option><option value="WASTE">Waste</option></select>}</header>
      {loading ? <div className="report-empty">Loading report data…</div> : active === 'inventory' ? <InventoryReport status={inventoryStatus} items={inventory} /> : active === 'low-stock' ? <LowStockReport items={lowStock} /> : active === 'movements' ? <MovementReport items={filteredMovements} /> : <EmployeeReport employees={employees} summary={employeeSummary} departments={departments} />}
    </section>
  </motion.main></div>;
}
function InventoryReport({ status, items }) { return <><div className="report-chart-grid"><article><h3>Inventory health</h3><div className="report-chart"><ResponsiveContainer><PieChart><Pie data={status} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="80%" paddingAngle={3}>{status.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="report-legend">{status.map((item) => <span key={item.name}><i style={{ background: item.color }} />{item.name}: <b>{item.value}</b></span>)}</div></article><article><h3>Stock by item</h3><div className="report-chart"><ResponsiveContainer><BarChart data={items.slice(0, 8)}><XAxis dataKey="name" hide /><YAxis /><Tooltip /><Bar dataKey="currentStock" fill="#c43b30" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></article></div><InventoryTable items={items} /></>; }
function LowStockReport({ items }) { return <><div className="report-callout"><strong>{items.length} items need attention</strong><span>Restock low or out-of-stock inventory to keep operations moving.</span></div><InventoryTable items={items} shortage /></>; }
function MovementReport({ items }) { return <div className="report-table-wrap"><table className="report-table"><thead><tr><th>Date</th><th>Item</th><th>Type</th><th>Quantity</th><th>Previous</th><th>New</th><th>Reason</th></tr></thead><tbody>{items.length ? items.map((item) => <tr key={item.id}><td>{new Date(item.createdAt).toLocaleString()}</td><td>{item.item?.name || '—'}</td><td><span className="report-type">{item.type}</span></td><td>{item.quantity}</td><td>{item.previousStock}</td><td>{item.newStock}</td><td>{item.reason}</td></tr>) : <tr><td colSpan="7">No stock movements match this filter.</td></tr>}</tbody></table></div>; }
function EmployeeReport({ employees, summary, departments }) { return <><div className="report-chart-grid"><article><h3>Department distribution</h3><div className="report-chart"><ResponsiveContainer><BarChart data={departments}><XAxis dataKey="name" hide /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="employees" fill="#3d7f48" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></article><article className="report-insight"><span>Active workforce</span><strong>{summary.activeEmployees || 0}</strong><small>of {summary.totalEmployees || 0} employees</small></article></div><div className="report-table-wrap"><table className="report-table"><thead><tr><th>Employee</th><th>Department</th><th>Designation</th><th>Joined</th><th>Status</th></tr></thead><tbody>{employees.length ? employees.map((employee) => <tr key={employee.id}><td>{employee.firstName} {employee.lastName}</td><td>{employee.department}</td><td>{employee.designation}</td><td>{employee.joiningDate ? new Date(employee.joiningDate).toLocaleDateString() : '—'}</td><td>{employee.status}</td></tr>) : <tr><td colSpan="5">No employee records are available.</td></tr>}</tbody></table></div></>; }
function InventoryTable({ items, shortage }) { return <div className="report-table-wrap"><table className="report-table"><thead><tr><th>Item</th><th>Category</th><th>Current stock</th><th>Minimum</th>{shortage && <th>Shortage</th>}<th>Unit</th><th>Value</th><th>Status</th></tr></thead><tbody>{items.length ? items.map((item) => <tr key={item.id}><td>{item.name}<small>{item.sku}</small></td><td>{item.category?.name || '—'}</td><td>{item.currentStock}</td><td>{item.minimumStock}</td>{shortage && <td>{Math.max(number(item.minimumStock) - number(item.currentStock), 0)}</td>}<td>{item.unit}</td><td>{money.format(number(item.currentStock) * number(item.costPerUnit))}</td><td>{statusLabel[item.status] || item.status}</td></tr>) : <tr><td colSpan={shortage ? 8 : 7}>No inventory records are available.</td></tr>}</tbody></table></div>; }
