import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import Sidebar from '../components/Sidebar';
import { inventoryApi } from '../services/inventoryApi';
import { salesApi } from '../services/salesApi';
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
const n = (v) => Number(v || 0);
const salePrice = (item) => n(item.sellingPrice ?? item.costPerUnit);

export default function Sales() {
  const [sales, setSales] = useState([]), [summary, setSummary] = useState({}), [inventory, setInventory] = useState([]), [page, setPage] = useState({}), [filters, setFilters] = useState({ search: '', status: '', paymentStatus: '', page: 1, limit: 10 }), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState(''), [cart, setCart] = useState([]), [createOpen, setCreateOpen] = useState(false), [detail, setDetail] = useState(null), [customer, setCustomer] = useState(''), [paymentStatus, setPaymentStatus] = useState('PAID'), [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const [list, overview, products] = await Promise.all([salesApi.getSales(filters), salesApi.getSummary(), inventoryApi.getInventory({ page: 1, limit: 100 })]); setSales(list.data.sales || []); setPage(list.data.pagination || {}); setSummary(overview.data.summary || {}); setInventory(products.data.items || []); setError(''); } catch (e) { setError(e.message || 'Sales could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, filters.search ? 250 : 0); return () => clearTimeout(timer); }, [filters]);
  const change = (key, value) => setFilters((f) => ({ ...f, [key]: value, page: key === 'page' ? value : 1 }));
  const add = (item) => setCart((current) => current.some((x) => x.id === item.id) ? current : [...current, { ...item, costPerUnit: salePrice(item), quantity: 1 }]);
  const updateQty = (id, quantity) => setCart((current) => current.map((item) => item.id === id ? { ...item, quantity: Math.max(1, Math.min(n(quantity), n(item.currentStock))) } : item));
  const subtotal = cart.reduce((sum, item) => sum + salePrice(item) * n(item.quantity), 0);
  const create = async () => { if (!cart.length) return setError('Add at least one inventory item to the sale.'); setSaving(true); try { await salesApi.createSale({ customerName: customer, paymentStatus, items: cart.map((item) => ({ inventoryItemId: item.id, quantity: item.quantity })) }); setCart([]); setCustomer(''); setCreateOpen(false); setNotice('Sale created and inventory updated successfully.'); await load(); } catch (e) { setError(e.message || 'Sale could not be created.'); } finally { setSaving(false); } };
  const openDetail = async (sale) => { try { const response = await salesApi.getSale(sale.id); setDetail(response.data.sale); } catch (e) { setError(e.message); } };
  return <div className="dashboard-shell"><Sidebar /><motion.main className="sales-page" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}><header className="sales-header"><div><span className="eyebrow">Sales</span><h1>Sales</h1><p>Track and manage your business sales.</p></div><div><button className="secondary-button" type="button" onClick={load}>Refresh</button><button className="primary-button" type="button" onClick={() => setCreateOpen(true)}>+ Create sale</button></div></header>{error && <div className="form-message form-message--error">{error}<button onClick={() => setError('')}>×</button></div>}{notice && <div className="form-message form-message--success">{notice}<button onClick={() => setNotice('')}>×</button></div>}
  <section className="sales-kpis">{[['Total sales', summary.totalSales || 0], ['Revenue', money.format(n(summary.totalRevenue))], ['Completed', summary.completedSales || 0], ['Pending payments', summary.pendingPayments || 0], ['Average sale', money.format(n(summary.averageSaleValue))]].map((card, index) => <motion.article key={card[0]} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }}><span>{card[0]}</span><strong>{card[1]}</strong></motion.article>)}</section>
  <section className="sales-chart-panel"><div><span className="eyebrow">Performance</span><h2>Recent sales value</h2></div><div className="sales-chart"><ResponsiveContainer><BarChart data={sales.slice(0, 8).reverse()}><XAxis dataKey="saleNumber" hide /><YAxis /><Tooltip /><Bar dataKey="totalAmount" fill="#c43b30" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></section>
  <section className="sales-table-panel"><div className="sales-toolbar"><input value={filters.search} onChange={(e) => change('search', e.target.value)} placeholder="Search sale or customer" /><select value={filters.status} onChange={(e) => change('status', e.target.value)}><option value="">All statuses</option><option value="COMPLETED">Completed</option><option value="PENDING">Pending</option><option value="CANCELLED">Cancelled</option></select><select value={filters.paymentStatus} onChange={(e) => change('paymentStatus', e.target.value)}><option value="">All payments</option><option value="PAID">Paid</option><option value="PENDING">Pending</option><option value="PARTIAL">Partial</option></select></div><div className="sales-table-wrap"><table className="sales-table"><thead><tr><th>Sale</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th>Date</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan="8">Loading sales…</td></tr> : sales.length ? sales.map((sale) => <tr key={sale.id}><td>{sale.saleNumber}</td><td>{sale.customerName || 'Walk-in customer'}</td><td>{sale.items.length}</td><td>{money.format(sale.totalAmount)}</td><td>{sale.paymentStatus}</td><td>{sale.status}</td><td>{new Date(sale.createdAt).toLocaleDateString()}</td><td><button type="button" onClick={() => openDetail(sale)}>View</button></td></tr>) : <tr><td colSpan="8">No sales match these filters.</td></tr>}</tbody></table></div><footer className="sales-pagination"><span>Page {page.page || 1} of {page.totalPages || 1}</span><button disabled={n(page.page) <= 1} onClick={() => change('page', n(page.page) - 1)}>Previous</button><button disabled={n(page.page) >= n(page.totalPages)} onClick={() => change('page', n(page.page) + 1)}>Next</button></footer></section>
  <AnimatePresence>{createOpen && <div className="sales-overlay" onClick={() => setCreateOpen(false)}><motion.aside className="sales-create" initial={{ x: 40, opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: 40, opacity: 0 }} onClick={(e) => e.stopPropagation()}><header><div><span className="eyebrow">New sale</span><h2>Create sale</h2></div><button onClick={() => setCreateOpen(false)}>×</button></header><div className="sales-pos"><section><input placeholder="Customer name (optional)" value={customer} onChange={(e) => setCustomer(e.target.value)} /><h3>Available inventory</h3>{inventory.filter((item) => n(item.currentStock) > 0).map((item) => <button className="sales-product" key={item.id} type="button" onClick={() => add(item)}><span><strong>{item.name}</strong><small>{item.currentStock} {item.unit} available</small></span><b>{money.format(item.costPerUnit || 0)}</b></button>)}</section><section className="sales-cart"><h3>Current sale</h3>{cart.length ? cart.map((item) => <div key={item.id}><span>{item.name}<small>{money.format(item.costPerUnit || 0)} each</small></span><input type="number" min="1" max={item.currentStock} value={item.quantity} onChange={(e) => updateQty(item.id, e.target.value)} /><b>{money.format(n(item.costPerUnit) * n(item.quantity))}</b><button onClick={() => setCart((c) => c.filter((x) => x.id !== item.id))}>×</button></div>) : <p>Select inventory items to begin.</p>}<label>Payment status<select value={paymentStatus} onChange={(e) => setPaymentStatus(e.target.value)}><option value="PAID">Paid</option><option value="PENDING">Pending</option><option value="PARTIAL">Partial</option></select></label><footer><span>Subtotal</span><strong>{money.format(subtotal)}</strong></footer><button className="primary-button" disabled={saving || !cart.length} onClick={create}>{saving ? 'Creating…' : 'Create sale'}</button></section></div></motion.aside></div>}{detail && <div className="sales-overlay" onClick={() => setDetail(null)}><motion.aside className="sales-detail" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 20 }} onClick={(e) => e.stopPropagation()}><header><div><span className="eyebrow">Sale details</span><h2>{detail.saleNumber}</h2></div><button onClick={() => setDetail(null)}>×</button></header><p>{detail.customerName || 'Walk-in customer'} · {detail.paymentStatus} · {detail.status}</p><div className="sales-detail-items">{detail.items.map((item) => <div key={item.id}><span>{item.inventoryItem.name}</span><span>{item.quantity} × {money.format(item.unitPrice)}</span><strong>{money.format(item.totalPrice)}</strong></div>)}</div><footer><span>Subtotal</span><strong>{money.format(detail.subtotal)}</strong><span>Discount</span><strong>{money.format(detail.discount)}</strong><span>Tax</span><strong>{money.format(detail.tax)}</strong><span>Total</span><strong>{money.format(detail.totalAmount)}</strong></footer></motion.aside></div>}</AnimatePresence></motion.main></div>;
}
